-- MySQL Script generated by MySQL Workbench
-- Sat May  1 22:44:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema base
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base` DEFAULT CHARACTER SET utf8 ;
USE `base` ;

-- -----------------------------------------------------
-- Table `base`.`producteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`producteur` (
  `id` INT NOT NULL,
  `first name` VARCHAR(30) NULL,
  `last name` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `company name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`catégorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`catégorie` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`avis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`avis` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`produit` (
  `id` INT NOT NULL,
  `catégorie_id` INT NOT NULL,
  `avis_id` INT NOT NULL,
  `producteur_id` INT NOT NULL,
  `Prix` FLOAT NULL,
  PRIMARY KEY (`id`, `catégorie_id`, `avis_id`, `producteur_id`),

  CONSTRAINT `fk_produit_catégorie1`
    FOREIGN KEY (`catégorie_id`)
    REFERENCES `base`.`catégorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_commentaire1`
    FOREIGN KEY (`avis_id`)
    REFERENCES `base`.`avis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_producteur1`
    FOREIGN KEY (`producteur_id`)
    REFERENCES `base`.`producteur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`blog` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`internaute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`internaute` (
  `id` INT NOT NULL,
  `blog_id` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Prénom` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `blog_id`),
  INDEX `fk_internaute_blog1_idx` (`blog_id` ASC) VISIBLE,
  CONSTRAINT `fk_internaute_blog1`
    FOREIGN KEY (`blog_id`)
    REFERENCES `base`.`blog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`avis_internaute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`avis_internaute` (
  `avis_id` INT NOT NULL,
  `internaute_id` INT NOT NULL,
  `internaute_blog_id` INT NOT NULL,
  PRIMARY KEY (`avis_id`, `internaute_id`, `internaute_blog_id`),

  CONSTRAINT `fk_avis_has_internaute_avis1`
    FOREIGN KEY (`avis_id`)
    REFERENCES `base`.`avis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avis_has_internaute_internaute1`
    FOREIGN KEY (`internaute_id` , `internaute_blog_id`)
    REFERENCES `base`.`internaute` (`id` , `blog_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
